workflows:
  ios_kmp_test:
    name: iOS KMP Test
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Build KMP XCFramework
        script: |
          chmod +x gradlew
          cd shared
          ../gradlew assembleSharedKitDebugXCFramework
      - name: Generate Xcode project
        script: |
          cd iosApp
          xcodegen generate --spec xcodegen.yml
      - name: Build iOS app for Simulator (Debug, no tests)
        script: |
          xcodebuild build \
            -project "iosApp/iosApp.xcodeproj" \
            -scheme "iosApp" \
            -sdk iphonesimulator \
            -configuration Debug
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
