workflows:
  ios_kmp_test:
      name: iOS KMP Test
      instance_type: mac_mini_m2
      environment:
        xcode: 16.4
      scripts:
        - name: Install XcodeGen
          script: |
            brew install xcodegen
        - name: Build KMP XCFramework
          script: |
            chmod +x gradlew
            ./gradlew :shared:assembleSharedKitDebugXCFramework
        - name: Generate Xcode project
          script: |
            cd iosApp
            xcodegen generate --spec xcodegen.yml
        - name: Build iOS app for Simulator (Debug, no tests)
          script: |
            xcodebuild build \
              -project "iosApp/iosApp.xcodeproj" \
              -scheme "iosApp" \
              -sdk iphonesimulator \
              -configuration Debug
      artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
